### ISSUE TITLE
Add more detail to reward vault section

### ISSUE THREAD

**Issue by camiinthisthang** [berachain/docs-old#288]
### What is the issue?

Add more documentation explaining how reward vaults are used. Specifically:
- clarify a protocol can have multiple reward vaults
- clarify the concept of a receipt token
- clarify they're role in PoL (these are the addresses that receive BGT from validators
- add visuals

### Where did you find it?

https://docs.berachain.com/learn/pol/rewardvaults

**Comment by imanpajand** [comment]
you can find the formula of BGT reward vault in discord.

**Comment by codingwithmanny** [comment]
Closing this because it was fixed in #289
