### ISSUE TITLE
CORE - Incentives

### ISSUE THREAD

**Issue by codingwithmanny** [berachain/docs-old#357]
**Context:**
Review this section to make sure that all wording matches the latest information.

**Page:**
https://docs.berachain.com/learn/pol/incentives

**Tasks:**
1. Verify information

**Comment by camiinthisthang** [comment]
Changes merged into next with PR [344](https://github.com/berachain/docs/pull/344/files)

**Comment by DonBera** [comment]
can I have the preview link of this? I can't find it anymore and I have already the final version reviewed with the Quants! muchas gracias

**Comment by codingwithmanny** [comment]
Hey @DonBera preview link should be:
- https://berachain-docs-core-next.vercel.app/learn/pol/incentives

**Comment by DonBera** [comment]
can't comment over here sharing a google doc to @camiinthisthang in DM
