### ISSUE TITLE
CORE - Participants

### ISSUE THREAD

**Issue by codingwithmanny** [berachain/docs-old#359]
**Context:**
Review this section to make sure that all wording matches the latest information.

**Page:**
https://docs.berachain.com/learn/pol/participants

**Tasks:**
1. Verify information

**Comment by camiinthisthang** [comment]
Changes merged into next with [346](https://github.com/berachain/docs/pull/346/files#diff-a2d4e79eb753d1c7949bf499739113f71515c57ad142955f47b7af437cfabc3c) PR
