### ISSUE TITLE
CORE - Tokens $BGT

### ISSUE THREAD

**Issue by codingwithmanny** [berachain/docs-old#366]
**Context:**
Review this section to make sure that all wording matches the latest information.

**Page:**
https://docs.berachain.com/learn/pol/tokens/bgt

**Tasks:**
1. Verify information

**Comment by camiinthisthang** [comment]
@DonBera https://berachain-docs-core-next-git-contentchecks.berachain-staging.com/learn/pol/tokens/bgt
