### ISSUE TITLE
BEX dev - Guides - Get Spot Prices

### ISSUE THREAD

**Issue by larrythecucumber321** [berachain/docs-old#394]
**Context:**
Review this section to make sure that all wording matches the latest information.

**Page:**
https://berachain-docs-bex-git-feat-bex-v2-berachain1.vercel.app/developers/guides/spot-prices

**Tasks:**
- Add developer guide on SDK usage

**Comment by blackbera** [comment]
Closing this issue as this is not supported in the Balancer V3 SDK
