### ISSUE TITLE
BEND - Coming Soon

### ISSUE THREAD

**Issue by codingwithmanny** [berachain/docs-old#396]
**Context:**
Bend docs will be revised and re-released at a later time. In the meantime the main docs needs redone as "coming soon".

**Site:**
https://docs.bend.berachain.com

**Tasks:**
1. BEND - Make all pages to bend redirect to the root page "/"
2. BEND - Homepage - Remove links to: "Bend User Guide", "Try Bend", "Berachain Faucet"
3. BEND - Add the text "Coming soon" on the home page
4. CORE - More Docs Dropdown - Make Bend a disabled link with (Coming Soon)
5. BEX - More Docs Dropdown - Make Bend a disabled link with (Coming Soon)
6. BERPS - More Docs Dropdown - Make Bend a disabled link with (Coming Soon)

**Comment by blackbera** [comment]
@DonBera your previews for everything here ser 

Make sure to check that BEND only says coming soon and the links mentioned in the issue cannot be accessed. 
BEND - https://berachain-docs-bend-next.vercel.app/

Associated core dapps to make sure BEND docs are not accessible
CORE - https://berachain-docs-core-next.vercel.app/
BERPS - https://berachain-docs-berps-next.vercel.app/
BEX - https://berachain-docs-bex-next.vercel.app/

**Comment by blackbera** [comment]
Pull 439 is the correct PR I'm closing #407 
https://github.com/berachain/docs/pull/439

**Comment by DonBera** [comment]
- Shall we call it Beraswap also on the homepage of the doc vs. SWAP? 
- From the homepage there are on the bottom other link to "Other Berachain Resources" in which it is still called **BEX** and there is still a reference of **BGT Station** that now is part of **HUB** 
- Last but not least **Beratrail** changed naming in "**Berascan**"

**Comment by blackbera** [comment]
cc @DonBera 
Preview link here for you again - https://berachain-docs-core-next.vercel.app/
PR - https://github.com/berachain/docs/pull/498
