### ISSUE TITLE
BERPS - Coming Soon

### ISSUE THREAD

**Issue by codingwithmanny** [berachain/docs-old#397]
**Context:**
Berps docs will be revised and re-released at a later time. In the meantime the main docs needs redone as "coming soon".

**Site:**
https://docs.berps.berachain.com

**Tasks:**
1. BERPS - Make all pages to bend redirect to the root page "/"
2. BERPS - Homepage - Remove links to: "Berps User Guide", "Developers", "Berachain Faucet"
3. BERPS - Add the text "Coming soon" on the home page
4. CORE - More Docs Dropdown - Make Berps a disabled link with (Coming Soon)
5. BEX - More Docs Dropdown - Make Berps a disabled link with (Coming Soon)
6. BEND - More Docs Dropdown - Make Berps a disabled link with (Coming Soon)

**Comment by blackbera** [comment]
@DonBera 
Main link to check. Ensure that BERPs only has coming soon and the links mentioned above are removed

BERPS - https://berachain-docs-berps-next.vercel.app/

Check the other dapps to make sure that the BERPS link is not accessible. 
BEX - https://berachain-docs-bex-next.vercel.app/
BEND - https://berachain-docs-bend-next.vercel.app/
CORE - https://berachain-docs-core-next.vercel.app/

**Comment by blackbera** [comment]
PR - https://github.com/berachain/docs/pull/439

**Comment by DonBera** [comment]
links to be checked at the very end or probably once we publish it as it's quite confusing like this as it's redirecting me to previous doc

**Comment by blackbera** [comment]
moving this to blocked @DonBera as we will need the links before it can be fully reviewed

**Comment by DonBera** [comment]
fine for me
