### ISSUE TITLE
CORE - Quickstart: Run A Node

### ISSUE THREAD

**Issue by codingwithmanny** [berachain/docs-old#412]
**Context:**
Review to make sure that all the pages reflect latest information.

**Page:**
https://docs.berachain.com/nodes/quickstart

**Tasks:**
1. Validator information is accurate
2. Update mention different binaries
3. Ensure rpc auth is set correctly
4. Mention that the latest block height is the consensus block height
5. Add a way to check the current consensus block height

**Comment by codingwithmanny** [comment]
Page to review:
- https://berachain-docs-core-next.vercel.app/nodes/quickstart

**Comment by DonBera** [comment]
ok for me. 
@codingwithmanny can you check if this links to the latest version? [pre-built binary from here](https://github.com/berachain/beacon-kit/releases)
